### ISSUE TITLE
Feature request: pluggable transports

### ISSUE THREAD

**Issue by emdin** [AmpersandJS/ampersand-sync#21]
Ampersand-sync can be upgraded to work on server, to do so xhr or any other transport should be pluggable. Something along the lines:
```javascript
var request = require('request');
var xhr = require('xhr');
var sync = require('ampersand-sync')({ 
    transport: (typeof window === 'undefined')? request: xhr 
});
```

**Comment by naugtur** [comment]
Is there an idea how you (maintainers) would like it to work? I could implement that while making the switch to xhr v2.0
I'd just prefer to know your opinion before I submit a PR

**Comment by naugtur** [comment]
This got accidentally done in xhr2-and-node branch.

```javascript
var sync = require("ampersand-sync/core")(whateverXhrYouWant)
```

Also, if you just wanted to switch between `xhr` for the browser and `request` for node, that's going to happen without any setup.
