### ISSUE TITLE
Offline support?

### ISSUE THREAD

**Issue by meongx** [AmpersandJS/ampersand-sync#43]
In the [introductory post](https://blog.andyet.com/2014/06/25/introducing-ampersand-js) Point 10, "*Embrace offline-first mentality and ServiceWorker all the things as soon as we can*"

I don't (yet) see any built-in offline capability in the source. Is it planned in the future or is it up to the app developer to actually do it?

**Comment by lukekarrys** [comment]
Hey @meongx, thanks for the question! I think at this point it would be up to the app developer to implement offline-first functionality in their app. There could definitely be something like `ampersand-model-offline` (if there isn't already somewhere on npm) which could handle offline capabilities and syncing those, but as of now there isn't anything like that in core.
