### ISSUE TITLE
Getting access to resp w/ cookie?

### ISSUE THREAD

**Issue by EvanCarroll** [AmpersandJS/ampersand-sync#49]
Is it possible to get access to a Set-Cookie in the `success` cb?

**Comment by EvanCarroll** [comment]
I see, it comes in the `options` (third argument) to the cb.

    success( model, testResponse, options ) {
        var xhr = options.xhr;

However, XHR doesn't provide a helper for reading the cookie info: https://github.com/Raynos/xhr/issues/76

**Comment by naugtur** [comment]
As I responded in https://github.com/Raynos/xhr/issues/76 I suggest using a separate function for that. For ampersand-sync it'd be an added benefit of using the same implementation in the browser and node (`request` has some support fro cookies, but only for sending them if I read correctly)
