### ISSUE TITLE
XHR2 not sending err.message in it's failure response, assumed to be there.

### ISSUE THREAD

**Issue by EvanCarroll** [AmpersandJS/ampersand-sync#50]
In the XHR2 branch, getting the following 

```text
     Uncaught TypeError: Cannot read property 'message' of null
      at Request._callback (/home/ecarroll/code/samp/node_modules/ampersand-model/node_modules/ampersand-sync/core.js:114:73)
      at Request.self.callback (/home/ecarroll/code/samp/node_modules/ampersand-model/node_modules/ampersand-sync/node_modules/request/request.js:354:22)
```

The conditionals are wrong. Patch attached.

**Comment by EvanCarroll** [comment]
Pull request.. https://github.com/AmpersandJS/ampersand-sync/pull/51

**Comment by naugtur** [comment]
It seems to me that the PR is doing far too much. Let me commit a fix to this issue that I think will suffice.

**Comment by naugtur** [comment]
try with https://github.com/AmpersandJS/ampersand-sync/commit/95ec785aa11632af8acc666f0ef60394c69473be

I believe it addresses this issue and #52

**Comment by EvanCarroll** [comment]
It doesn't address #52, #52 was explicitly about returning the error as a javascript object if the body was JSON.
