### ISSUE TITLE
Ampersand Sync + Node Request

### ISSUE THREAD

**Issue by Freyert** [AmpersandJS/ampersand-sync#57]
How does one go about using the `request` library instead of the `xhr` library for models?

I asked a question on [StackOverflow](http://stackoverflow.com/questions/31437898/using-ampersand-sync-with-nodes-request-library) if you want some bonus points.

**Comment by naugtur** [comment]
All you have to do is wait for the 4.0 to get released and used as dependency in model. I'm close to releasing sync@4.0 so it's not a long wait.

Once it's there, you just use ampersand-sync in nodejs and it works.

**Comment by lukekarrys** [comment]
Thanks to all @naugtur's hard work (!!!), v4 is published and this can be closed :smile:
