### ISSUE TITLE
XHR2 not available from npm

### ISSUE THREAD

**Issue by herkyl** [AmpersandJS/ampersand-sync#59]
How come the version 3.0.7 installed from npm is using xhr 1?

**Comment by naugtur** [comment]
ampersand-sync will use xhr2 in 4.0 (see other issues and PRs here)
master branch contains references to xhr2 because ampersand-sync@4.0 will get released within a few days from now and we're in the middle of a big merge + browser support check

**Comment by herkyl** [comment]
Thanks!
