### ISSUE TITLE
Peculiar behaviour with header override

### ISSUE THREAD

**Issue by dhritzkiv** [AmpersandJS/ampersand-sync#69]
With the latest ampersand-sync, overriding request headers can result in incorrectly concatenated header lines.

[Here's a gist](http://requirebin.com/?gist=2a6910992b2fff56c570) showing that passing in `{"Content-Type": "application/json}"` as a headers option results in the outgoing request header value of `application/json, application/json`. The gist makes the same request with `ampersand-sync` (broken here), as well as `xhr` (fine here), which might suggest the problem lies in `ampersand-sync`

Tested with both Chrome and Safari using POST requests.

**Comment by naugtur** [comment]
That's an issue with case sensitivity in xhr. This PR fixes it as a side effect: https://github.com/Raynos/xhr/pull/90

I'll release it and bump version in sync

**Comment by dhritzkiv** [comment]
Sounds good

**Comment by dhritzkiv** [comment]
Is an npm version bump coming soon? ☺️

**Comment by naugtur** [comment]
It's out as of now.
