### ISSUE TITLE
Update Readme to reflect actual contributors :)

### ISSUE THREAD

**Issue by HenrikJoreteg** [AmpersandJS/ampersand-sync#70]
@naugtur and @pgilad, you should be listed prominently in the Readme, and the silly old line of "follow henrik" should go away :)

I'd also like to make you both part of the core team if you're ok with that.

**Comment by naugtur** [comment]
I'd be happy to get added to the team.

**Comment by pgilad** [comment]
Thanks! I think I'm already in the core team ;-)

**Comment by HenrikJoreteg** [comment]
haha, oh good! @pgilad then you just need to be here: http://ampersandjs.com/contribute will fix

**Comment by HenrikJoreteg** [comment]
fixed: http://ampersandjs.com/contribute  thanks!

**Comment by pgilad** [comment]
:clap: Thanks!

**Comment by naugtur** [comment]
yay :trophy: 

I made a proposal of readme change. Didn't want to decide who to list or not, so I linked to everyone.

**Comment by kamilogorek** [comment]
Cheers guys! :)

**Comment by naugtur** [comment]
Cześć Kamil ;)

**Comment by kamilogorek** [comment]
Cześć! Long time no see :)
